/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Menu;
import clases.ProductoCarta;
import java.awt.Color;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pabli
 */
public class carrito extends javax.swing.JFrame {

    private final String ventana;
    private final restaurating sesion;
    private Double precio;

    /**
     * Creates new form principal
     *
     * @param ventana
     * @param sesion
     */
    public carrito(String ventana, restaurating sesion) {
        initComponents();

        escalarImagenMenu();
        escalarImagenConfigurar();
        escalarImagenPago();
        escalarImagenSalir();
        escalarImagenEliminar();
        this.ventana = ventana;
        this.sesion = sesion;
        this.precio = 0.0;

        if (!btnCaja.isEnabled()) {
            avisoPago.setText("*Debe añadir algún producto al carrito para poder realizar el pago.");
        } else {
            avisoPago.setText("");
        }

        tablaCarrito.getColumn("Tipo").setMaxWidth(120);
        tablaCarrito.getColumn("Cantidad").setMaxWidth(500);
        tablaCarrito.getColumn("Cantidad").setPreferredWidth(120);
        tablaCarrito.getColumn("Precio").setPreferredWidth(120);
        tablaCarrito.getColumn("Precio").setMaxWidth(200);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tablaCarrito.getColumn("Precio").setCellRenderer(rightRenderer);
        DefaultTableCellRenderer render = (DefaultTableCellRenderer) tablaCarrito.getTableHeader().getDefaultRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);
        tablaCarrito.getTableHeader().setReorderingAllowed(false);
        tablaCarrito.setRowHeight(30);
        tablaCarrito.getTableHeader().setFont(new java.awt.Font("DIalog", 0, 18));

        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPagina = new javax.swing.JLabel();
        btnCaja = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        avisoPago = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        precioCambiado = new javax.swing.JLabel();
        btnEliminarSeleccionado = new javax.swing.JButton();
        btnEliminarTodo = new javax.swing.JButton();
        btnAnadirMenu = new javax.swing.JButton();
        btnAnadirProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrito");

        tituloPagina.setBackground(new java.awt.Color(255, 102, 102));
        tituloPagina.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tituloPagina.setForeground(new java.awt.Color(255, 102, 102));
        tituloPagina.setText("Carrito");

        btnCaja.setBackground(new java.awt.Color(255, 102, 102));
        btnCaja.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCaja.setText("Pasar a Caja");
        btnCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaja.setEnabled(false);
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCajaMouseExited(evt);
            }
        });
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        avisoPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        avisoPago.setForeground(new java.awt.Color(255, 0, 51));

        tablaCarrito.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Productos", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCarrito);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("IMPORTE TOTAL:");

        precioCambiado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        precioCambiado.setForeground(new java.awt.Color(0, 0, 0));
        precioCambiado.setText("0.00 €");

        btnEliminarSeleccionado.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarSeleccionado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminarSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSeleccionado.setText("Eliminar Seleccionado");
        btnEliminarSeleccionado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarSeleccionado.setEnabled(false);
        btnEliminarSeleccionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarSeleccionadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarSeleccionadoMouseExited(evt);
            }
        });
        btnEliminarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeleccionadoActionPerformed(evt);
            }
        });

        btnEliminarTodo.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarTodo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTodo.setText("Eliminar Todo");
        btnEliminarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTodo.setEnabled(false);
        btnEliminarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarTodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarTodoMouseExited(evt);
            }
        });
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });

        btnAnadirMenu.setBackground(new java.awt.Color(255, 102, 102));
        btnAnadirMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAnadirMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirMenu.setText("Añadir Menú");
        btnAnadirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirMenuMouseExited(evt);
            }
        });
        btnAnadirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirMenuActionPerformed(evt);
            }
        });

        btnAnadirProducto.setBackground(new java.awt.Color(255, 102, 102));
        btnAnadirProducto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAnadirProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirProducto.setText("Añadir Producto");
        btnAnadirProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadirProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirProductoMouseExited(evt);
            }
        });
        btnAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avisoPago)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnadirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(tituloPagina))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioCambiado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarSeleccionado)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tituloPagina)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnadirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(precioCambiado))
                .addGap(208, 208, 208)
                .addComponent(avisoPago)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseEntered
        btnCaja.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnCajaMouseEntered

    private void btnCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseExited
        btnCaja.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnCajaMouseExited

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        pago vent = new pago("carrito", ventana, sesion);
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        regresoVentana(ventana);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarSeleccionadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionadoMouseEntered
        btnEliminarSeleccionado.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnEliminarSeleccionadoMouseEntered

    private void btnEliminarSeleccionadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionadoMouseExited
        btnEliminarSeleccionado.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnEliminarSeleccionadoMouseExited

    private void btnEliminarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionadoActionPerformed
        precio = 0.0;

        if (tablaCarrito.getValueAt(tablaCarrito.getSelectedRow(), 0).equals("Carta")) {
            for (int i = 0; i < sesion.productosCarta.size(); i++) {
                if (sesion.productosCarta.get(i).getProducto().equals(tablaCarrito.getValueAt(tablaCarrito.getSelectedRow(), 1))) {
                    sesion.productosCarta.get(i).setCantidad(0);
                    break;
                }
            }
        } else {
            for (int i = 0; i < sesion.menu.size(); i++) {
                if (sesion.menu.get(i).getProductos().equals(tablaCarrito.getValueAt(tablaCarrito.getSelectedRow(), 1))) {
                    sesion.menu.remove(i);
                    break;
                }
            }
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        modelo.removeRow(tablaCarrito.getSelectedRow());
        tablaCarrito.setModel(modelo);

        for (Menu m : sesion.menu) {
            precio += m.getPrecio();
        }
        for (ProductoCarta p : sesion.productosCarta) {
            if (p.getCantidad() != 0) {
                precio += p.getCantidad() * p.getPrecio();
            }
        }
        precio = Math.round(precio * 100.0) / 100.0;
        precioCambiado.setText(getTwoDecimals(precio) + " €");

        modelo.fireTableDataChanged();

        if (modelo.getRowCount() > 0) {
            tablaCarrito.setRowSelectionInterval(0, 0);
            btnEliminarSeleccionado.setEnabled(true);
            btnEliminarTodo.setEnabled(true);
            btnCaja.setEnabled(true);
        } else {
            btnEliminarSeleccionado.setEnabled(false);
            btnEliminarTodo.setEnabled(false);
            btnCaja.setEnabled(false);
        }
    }//GEN-LAST:event_btnEliminarSeleccionadoActionPerformed

    private void btnEliminarTodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTodoMouseEntered
        btnEliminarTodo.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnEliminarTodoMouseEntered

    private void btnEliminarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTodoMouseExited
        btnEliminarTodo.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnEliminarTodoMouseExited

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        sesion.menu.clear();
        sesion.productosCarta.clear();

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        int filas = tablaCarrito.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
        tablaCarrito.setModel(modelo);
        actualizarTabla();
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void btnAnadirMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMenuMouseEntered
        btnAnadirMenu.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnAnadirMenuMouseEntered

    private void btnAnadirMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMenuMouseExited
        btnAnadirMenu.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnAnadirMenuMouseExited

    private void btnAnadirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirMenuActionPerformed
        menu vent = new menu(sesion, "carrito", ventana);
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnadirMenuActionPerformed

    private void btnAnadirProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirProductoMouseEntered
        btnAnadirProducto.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnAnadirProductoMouseEntered

    private void btnAnadirProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirProductoMouseExited
        btnAnadirProducto.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnAnadirProductoMouseExited

    private void btnAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirProductoActionPerformed
        configuracion vent = new configuracion(sesion, "carrito", ventana);
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnadirProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoPago;
    private javax.swing.JButton btnAnadirMenu;
    private javax.swing.JButton btnAnadirProducto;
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnEliminarSeleccionado;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel precioCambiado;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables

    private void escalarImagenMenu() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/menu.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnAnadirMenu.setIcon(icon);
    }

    private void escalarImagenConfigurar() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/anadir.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnAnadirProducto.setIcon(icon);
    }
    
    private void escalarImagenPago() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cajaregistradora.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(80, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnCaja.setIcon(icon);
    }

    private void escalarImagenSalir() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/return.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnVolver.setIcon(icon);
    }
    
    private void escalarImagenEliminar() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/salir.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnEliminarSeleccionado.setIcon(icon);
        btnEliminarTodo.setIcon(icon);
    }

    public void regresoVentana(String ventana) {
        switch (ventana) {
            case "configuracion": {
                configuracion vent = new configuracion(sesion, "carrito", ventana);
                vent.setLocationRelativeTo(null);
                vent.setVisible(true);
                break;
            }
            case "menu": {
                menu vent = new menu(sesion, "carrito", ventana);
                vent.setLocationRelativeTo(null);
                vent.setVisible(true);
                break;
            }
            case "principal": {
                principal vent = new principal(sesion);
                vent.comprobarProductos();
                vent.setLocationRelativeTo(null);
                vent.setVisible(true);
                break;
            }
            default:
                break;
        }
    }

    public void comprobarProductos() {
        boolean carta = false;
        for (ProductoCarta prod : sesion.productosCarta) {
            if (prod.getCantidad() > 0) {
                carta = true;
                break;
            }
        }

        if (carta || sesion.menu.size() > 0) {
            btnCaja.setEnabled(true);
            btnEliminarTodo.setEnabled(true);
        } else {
            btnCaja.setEnabled(false);
            btnEliminarTodo.setEnabled(false);
        }

        if (!btnCaja.isEnabled()) {
            avisoPago.setText("*Debe añadir algún producto al carrito para poder gestionar el carrito.");
        } else {
            avisoPago.setText("");
        }
    }

    private void actualizarTabla() {
        precio = 0.0;

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        for (Menu m : sesion.menu) {
            String menu = "";
            if (m.getEnsaladilla() != null) {
                menu += "Ensaladilla Rusa";
                if (m.getPostre() != null || m.getCachopo() != null || m.getSalmon() != null || m.getCafe() != null) {
                    menu += " + ";
                }
            }
            if (m.getCroquetas() != null) {
                menu += "Croquetas de Atún";
                if (m.getPostre() != null || m.getCachopo() != null || m.getSalmon() != null || m.getCafe() != null) {
                    menu += " + ";
                }
            }
            if (m.getCachopo() != null) {
                menu += "Cachopo de Ternera";
                if (m.getPostre() != null || m.getCafe() != null) {
                    menu += " + ";
                }
            }
            if (m.getSalmon() != null) {
                menu += "Salmón al Horno";
                if (m.getPostre() != null || m.getCafe() != null) {
                    menu += " + ";
                }
            }
            if (m.getPostre() != null) {
                menu += "Postre Sorpresa";
            }
            if (m.getCafe() != null) {
                menu += "Café";
            }
            Object[] fila = {"Menú", menu, m.getCantidad(), getTwoDecimals(m.getPrecio()) + " €"};
            modelo.addRow(fila);

            precio += m.getPrecio();
        }

        for (ProductoCarta p : sesion.productosCarta) {
            if (p.getCantidad() != 0) {
                Double pr = p.getCantidad() * p.getPrecio();
                pr = Math.round(pr * 100.0) / 100.0;
                Object[] fila = {"Carta", p.getProducto(), p.getCantidad(), getTwoDecimals(pr) + " €"};
                modelo.addRow(fila);

                precio += p.getCantidad() * p.getPrecio();
            }
        }

        precio = Math.round(precio * 100.0) / 100.0;
        precioCambiado.setText(getTwoDecimals(precio) + " €");

        modelo.fireTableDataChanged();

        if (modelo.getRowCount() > 0) {
            tablaCarrito.setRowSelectionInterval(0, 0);
            btnEliminarSeleccionado.setEnabled(true);
            btnEliminarTodo.setEnabled(true);
            btnCaja.setEnabled(true);
        } else {
            btnEliminarSeleccionado.setEnabled(false);
            btnEliminarTodo.setEnabled(false);
            btnCaja.setEnabled(false);
        }
    }

    private static String getTwoDecimals(double value) {
        DecimalFormat df = new DecimalFormat("0.00");
        return df.format(value);
    }
}
