/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Menu;
import java.awt.Color;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pabli
 */
public class menu extends javax.swing.JFrame {

    private final String ventana;
    private final String ventana1;
    private Double precio;
    private final restaurating sesion;

    /**
     * Creates new form principal
     *
     * @param sesion
     * @param ventana
     * @param ventana1
     */
    public menu(restaurating sesion, String ventana, String ventana1) {
        initComponents();
        escalarImagenCarrito();
        escalarImagenPrimero1();
        escalarImagenPrimero2();
        escalarImagenSegundo1();
        escalarImagenSegundo2();
        escalarImagenPostre();
        escalarImagenCafe();
        escalarImagenSalir();
        escalarImagenInfo();
        primeroNada.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
        primeroNada.setFocusable(true);
        segundoNada.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
        segundoNada.setFocusable(true);

        this.ventana = ventana;
        this.ventana1 = ventana1;
        this.precio = 0.0;
        this.sesion = sesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPagina = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        primero1 = new javax.swing.JButton();
        primero2 = new javax.swing.JButton();
        primeroNada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        segundo1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        segundo2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        segundoNada = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        postre = new javax.swing.JButton();
        cafe = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        precioCambiado = new javax.swing.JLabel();
        avisoPago = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnMenosMenu = new javax.swing.JButton();
        cantidadMenu = new javax.swing.JTextField();
        btnMasMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir Menú");

        tituloPagina.setBackground(new java.awt.Color(255, 102, 102));
        tituloPagina.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tituloPagina.setForeground(new java.awt.Color(255, 102, 102));
        tituloPagina.setText("Menú del Día");

        btnCarrito.setBackground(new java.awt.Color(255, 102, 102));
        btnCarrito.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/carrito.png"))); // NOI18N
        btnCarrito.setText("Ver pedido actual");
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCarritoMouseExited(evt);
            }
        });
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("*La bebida se le indica al dependiente cuando vaya recoger el pedido.");

        primero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/ensaladilla.jpg"))); // NOI18N
        primero1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        primero1.setFocusable(false);
        primero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primero1MouseClicked(evt);
            }
        });

        primero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/croquetas.jpg"))); // NOI18N
        primero2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        primero2.setFocusable(false);
        primero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primero2MouseClicked(evt);
            }
        });

        primeroNada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        primeroNada.setFocusable(false);
        primeroNada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primeroNadaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Ensaladilla Rusa");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Croquetas de Atún");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Nada");

        segundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cachopo.jpg"))); // NOI18N
        segundo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        segundo1.setFocusable(false);
        segundo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segundo1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Cachopo de Ternera");

        segundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/salmon.jpg"))); // NOI18N
        segundo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        segundo2.setFocusable(false);
        segundo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segundo2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Salmón al Horno");

        segundoNada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        segundoNada.setFocusable(false);
        segundoNada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                segundoNadaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Nada");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("PRIMEROS");

        postre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/sorpresa.jpg"))); // NOI18N
        postre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postre.setFocusable(false);
        postre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postreMouseClicked(evt);
            }
        });

        cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cafe.jpg"))); // NOI18N
        cafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cafe.setFocusable(false);
        cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cafeMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Postre");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Café");

        btnAnadir.setBackground(new java.awt.Color(255, 102, 102));
        btnAnadir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadir.setText("Añadir");
        btnAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnadir.setEnabled(false);
        btnAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirMouseExited(evt);
            }
        });
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("PRECIO:");

        precioCambiado.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        precioCambiado.setForeground(new java.awt.Color(0, 0, 0));
        precioCambiado.setText("0,00 €");

        avisoPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avisoPago.setForeground(new java.awt.Color(255, 0, 51));
        avisoPago.setText("*Debe añadir un primero o un segundo como mínimo.");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("SEGUNDOS");

        btnInfo.setBackground(new java.awt.Color(255, 102, 102));
        btnInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setText("Ver información");
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("SOBRE ALERGIAS Y GLUTEN");

        btnMenosMenu.setBackground(new java.awt.Color(255, 102, 102));
        btnMenosMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenosMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenosMenu.setText("-");
        btnMenosMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosMenuMouseExited(evt);
            }
        });
        btnMenosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosMenuActionPerformed(evt);
            }
        });

        cantidadMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cantidadMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadMenu.setText("1");
        cantidadMenu.setEnabled(false);

        btnMasMenu.setBackground(new java.awt.Color(0, 153, 0));
        btnMasMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMasMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMasMenu.setText("+");
        btnMasMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasMenu.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel3)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel4)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(segundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(segundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(segundoNada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(primero1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloPagina)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(primero2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(58, 58, 58)
                                                .addComponent(primeroNada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avisoPago, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(precioCambiado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnMenosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cantidadMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnMasMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(125, 125, 125)
                                            .addComponent(jLabel6)
                                            .addGap(164, 164, 164)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(224, 224, 224)
                                                .addComponent(jLabel11)
                                                .addGap(75, 75, 75))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(postre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73)
                                                .addComponent(cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(47, 47, 47)))
                                .addGap(247, 247, 247)
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel9)
                .addGap(127, 127, 127)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(tituloPagina)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primero2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primeroNada, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primero1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundoNada, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(precioCambiado)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMasMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cantidadMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMenosMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisoPago)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseEntered
        btnCarrito.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnCarritoMouseEntered

    private void btnCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseExited
        btnCarrito.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnCarritoMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        regresoVentana();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        regresoVentana();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void primero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primero1MouseClicked
        if (!primero1.isFocusable()) {
            primero1.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            primero1.setFocusable(true);
            primero2.setFocusable(false);
            primero2.setBorder(BorderFactory.createEmptyBorder());
            primeroNada.setFocusable(false);
            primeroNada.setBorder(BorderFactory.createEmptyBorder());
        } else {
            primero1.setBorder(BorderFactory.createEmptyBorder());
            primero1.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_primero1MouseClicked

    private void primero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primero2MouseClicked
        if (!primero2.isFocusable()) {
            primero2.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            primero2.setFocusable(true);
            primero1.setFocusable(false);
            primero1.setBorder(BorderFactory.createEmptyBorder());
            primeroNada.setFocusable(false);
            primeroNada.setBorder(BorderFactory.createEmptyBorder());
        } else {
            primero2.setBorder(BorderFactory.createEmptyBorder());
            primero2.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_primero2MouseClicked

    private void primeroNadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeroNadaMouseClicked
        if (!primeroNada.isFocusable()) {
            primeroNada.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            primeroNada.setFocusable(true);
            primero1.setFocusable(false);
            primero1.setBorder(BorderFactory.createEmptyBorder());
            primero2.setFocusable(false);
            primero2.setBorder(BorderFactory.createEmptyBorder());
        } else {
            primeroNada.setBorder(BorderFactory.createEmptyBorder());
            primeroNada.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_primeroNadaMouseClicked

    private void segundo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundo1MouseClicked
        if (!segundo1.isFocusable()) {
            segundo1.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            segundo1.setFocusable(true);
            segundo2.setFocusable(false);
            segundo2.setBorder(BorderFactory.createEmptyBorder());
            segundoNada.setFocusable(false);
            segundoNada.setBorder(BorderFactory.createEmptyBorder());
        } else {
            segundo1.setBorder(BorderFactory.createEmptyBorder());
            segundo1.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_segundo1MouseClicked

    private void segundo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundo2MouseClicked
        if (!segundo2.isFocusable()) {
            segundo2.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            segundo2.setFocusable(true);
            segundo1.setFocusable(false);
            segundo1.setBorder(BorderFactory.createEmptyBorder());
            segundoNada.setFocusable(false);
            segundoNada.setBorder(BorderFactory.createEmptyBorder());
        } else {
            segundo2.setBorder(BorderFactory.createEmptyBorder());
            segundo2.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_segundo2MouseClicked

    private void segundoNadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_segundoNadaMouseClicked
        if (!segundoNada.isFocusable()) {
            segundoNada.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            segundoNada.setFocusable(true);
            segundo1.setFocusable(false);
            segundo1.setBorder(BorderFactory.createEmptyBorder());
            segundo2.setFocusable(false);
            segundo2.setBorder(BorderFactory.createEmptyBorder());
        } else {
            segundoNada.setBorder(BorderFactory.createEmptyBorder());
            segundoNada.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_segundoNadaMouseClicked

    private void postreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postreMouseClicked
        if (!postre.isFocusable()) {
            postre.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            postre.setFocusable(true);
            cafe.setFocusable(false);
            cafe.setBorder(BorderFactory.createEmptyBorder());
        } else {
            postre.setBorder(BorderFactory.createEmptyBorder());
            postre.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_postreMouseClicked

    private void cafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeMouseClicked
        if (!cafe.isFocusable()) {
            cafe.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000"), 3));
            cafe.setFocusable(true);
            postre.setFocusable(false);
            postre.setBorder(BorderFactory.createEmptyBorder());
        } else {
            cafe.setBorder(BorderFactory.createEmptyBorder());
            cafe.setFocusable(false);
        }
        cambioPrecio();
        botonPedir();
    }//GEN-LAST:event_cafeMouseClicked

    private void btnAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseEntered
        btnAnadir.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnAnadirMouseEntered

    private void btnAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseExited
        btnAnadir.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnAnadirMouseExited

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        Menu menu = new Menu();
        if (primero1.isFocusable()) {
            menu.setEnsaladilla("Ensaladilla Rusa");
        } else if (primero2.isFocusable()) {
            menu.setCroquetas("Croquetas de Atún");
        }
        if (segundo1.isFocusable()) {
            menu.setCachopo("Cachopo de Ternera");
        } else if (segundo2.isFocusable()) {
            menu.setSalmon("Salmón al Horno");
        }
        if (postre.isFocusable()) {
            menu.setPostre("Postre Sorpresa");
        } else if (cafe.isFocusable()) {
            menu.setCafe("Café");
        }
        menu.setPrecio(this.precio);

        String menuS = "";
        if (menu.getEnsaladilla() != null) {
            menuS += "Ensaladilla Rusa";
            if (menu.getPostre() != null || menu.getCachopo() != null || menu.getSalmon() != null || menu.getCafe() != null) {
                menuS += " + ";
            }
        }
        if (menu.getCroquetas() != null) {
            menuS += "Croquetas de Atún";
            if (menu.getPostre() != null || menu.getCachopo() != null || menu.getSalmon() != null || menu.getCafe() != null) {
                menuS += " + ";
            }
        }
        if (menu.getCachopo() != null) {
            menuS += "Cachopo de Ternera";
            if (menu.getPostre() != null || menu.getCafe() != null) {
                menuS += " + ";
            }
        }
        if (menu.getSalmon() != null) {
            menuS += "Salmón al Horno";
            if (menu.getPostre() != null || menu.getCafe() != null) {
                menuS += " + ";
            }
        }
        if (menu.getPostre() != null) {
            menuS += "Postre Sorpresa";
        }
        if (menu.getCafe() != null) {
            menuS += "Café";
        }

        menu.setProductos(menuS);
        menu.setCantidad(Integer.parseInt(cantidadMenu.getText()));
        sesion.menu.add(menu);
        regresoVentana();
        JOptionPane.showMessageDialog(null, "Menú añadido correctamente.");
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        btnInfo.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        btnInfo.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(this, "Los siguientes platos contienen gluten:\n - Croquetas de Atún\n - Cachopo de Ternera\n\nCualquier otra alergia o comentario, hagánoslo saber en la sección de observaciones en la página de pago.\nAdaptaremos el plato a sus necesidades.");
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnMenosMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMenuMouseEntered
        btnMenosMenu.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnMenosMenuMouseEntered

    private void btnMenosMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMenuMouseExited
        btnMenosMenu.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnMenosMenuMouseExited

    private void btnMenosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosMenuActionPerformed
        if (Integer.parseInt(cantidadMenu.getText()) > 1) {
            cantidadMenu.setText(String.valueOf((Integer.parseInt(cantidadMenu.getText()) - 1)));
        }
        cambioPrecio();
    }//GEN-LAST:event_btnMenosMenuActionPerformed

    private void btnMasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasMenuActionPerformed
        cantidadMenu.setText(String.valueOf((Integer.parseInt(cantidadMenu.getText()) + 1)));
        cambioPrecio();
    }//GEN-LAST:event_btnMasMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoPago;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMasMenu;
    private javax.swing.JButton btnMenosMenu;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton cafe;
    private javax.swing.JTextField cantidadMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton postre;
    private javax.swing.JLabel precioCambiado;
    private javax.swing.JButton primero1;
    private javax.swing.JButton primero2;
    private javax.swing.JButton primeroNada;
    private javax.swing.JButton segundo1;
    private javax.swing.JButton segundo2;
    private javax.swing.JButton segundoNada;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables

    private void escalarImagenCarrito() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/carrito.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnCarrito.setIcon(icon);
    }

    private void escalarImagenPrimero1() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/ensaladilla.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(primero1.getWidth(), primero1.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        primero1.setIcon(icon);
    }

    private void escalarImagenPrimero2() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/croquetas.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(primero2.getWidth(), primero2.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        primero2.setIcon(icon);
    }

    private void escalarImagenSegundo1() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cachopo.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(segundo1.getWidth(), segundo1.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        segundo1.setIcon(icon);
    }

    private void escalarImagenSegundo2() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/salmon.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(segundo2.getWidth(), segundo2.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        segundo2.setIcon(icon);
    }

    private void escalarImagenPostre() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/sorpresa.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(postre.getWidth(), postre.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        postre.setIcon(icon);
    }

    private void escalarImagenCafe() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cafe.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(cafe.getWidth(), cafe.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        cafe.setIcon(icon);
    }

    private void escalarImagenSalir() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/return.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnVolver.setIcon(icon);
    }

    private void escalarImagenInfo() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/info.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnInfo.setIcon(icon);
    }

    public void regresoVentana() {
        switch (ventana) {
            case "carrito": {
                carrito vent = new carrito(ventana1, sesion);
                vent.setLocationRelativeTo(null);
                vent.setVisible(true);
                this.dispose();
                break;
            }
            case "principal": {
                principal vent = new principal(sesion);
                vent.comprobarProductos();
                vent.setLocationRelativeTo(null);
                vent.setVisible(true);
                this.dispose();
                break;
            }
            default:
                break;
        }
    }

    private void cambioPrecio() {
        if ((primero1.isFocusable() || primero2.isFocusable()) && (segundo1.isFocusable() || segundo2.isFocusable())) {
            precio = 9.50 * Integer.parseInt(cantidadMenu.getText());
        } else if (primero1.isFocusable() || primero2.isFocusable() || segundo1.isFocusable() || segundo2.isFocusable()) {
            precio = 5.50 * Integer.parseInt(cantidadMenu.getText());
        } else {
            precio = 0.0;
        }
        precio = Math.round(precio * 100.0) / 100.0;
        precioCambiado.setText(getTwoDecimals(precio) + " €");
    }

    private void botonPedir() {
        if (precio != 0.0) {
            btnAnadir.setEnabled(true);
        } else {
            btnAnadir.setEnabled(false);
        }

        if (!btnAnadir.isEnabled()) {
            avisoPago.setText("*Debe añadir un primero o un segundo como mínimo.");
        } else {
            avisoPago.setText("");
        }
    }

    private static String getTwoDecimals(double value) {
        DecimalFormat df = new DecimalFormat("0.00");
        return df.format(value);
    }
}
