/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pabli
 */
public class pagado extends javax.swing.JFrame {

    /**
     * Creates new form principal
     *
     * @param hora
     */
    public pagado(String hora) {
        initComponents();
        escalarImagenQR();
        escalarImagenTarjeta();
        escalarImagenTicket();
        cambiarHoraRecogida();
        cambiarNumeroCola();

        horaRecogida.setText(hora);
        retire.setText("RETIRE");
        tarjeta.setText("LA TARJETA");
        btnRecoger.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPagina = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        qrIMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        horaRecogida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroCola = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        retire = new javax.swing.JLabel();
        tarjeta = new javax.swing.JLabel();
        recoger = new javax.swing.JLabel();
        recibo = new javax.swing.JLabel();
        btnRecoger = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedido Realizado");

        tituloPagina.setBackground(new java.awt.Color(255, 102, 102));
        tituloPagina.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tituloPagina.setForeground(new java.awt.Color(255, 102, 102));
        tituloPagina.setText("Pedido Realizado");

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Finalizar");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setEnabled(false);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        qrIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/codigoqr.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Recuerde recogerlo a las:");

        horaRecogida.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        horaRecogida.setForeground(new java.awt.Color(0, 51, 255));
        horaRecogida.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Su número en la cola será el:");

        numeroCola.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        numeroCola.setForeground(new java.awt.Color(0, 51, 255));
        numeroCola.setText("jLabel3");

        btnRetirar.setBackground(new java.awt.Color(255, 102, 102));
        btnRetirar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar Tarjeta");
        btnRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRetirarMouseExited(evt);
            }
        });
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        retire.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        retire.setForeground(new java.awt.Color(255, 102, 102));

        tarjeta.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tarjeta.setForeground(new java.awt.Color(255, 102, 102));

        recoger.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        recoger.setForeground(new java.awt.Color(255, 102, 102));

        recibo.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        recibo.setForeground(new java.awt.Color(255, 102, 102));

        btnRecoger.setBackground(new java.awt.Color(255, 102, 102));
        btnRecoger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRecoger.setForeground(new java.awt.Color(255, 255, 255));
        btnRecoger.setText("Recoger Recibo");
        btnRecoger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecoger.setEnabled(false);
        btnRecoger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecogerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecogerMouseExited(evt);
            }
        });
        btnRecoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecogerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(recoger, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRecoger, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloPagina)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qrIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                                .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(332, 332, 332))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(228, 228, 228)
                                        .addComponent(retire, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroCola))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horaRecogida)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(772, 772, 772))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(retire, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tituloPagina)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(qrIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(recoger, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecoger, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(horaRecogida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroCola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        restaurating vent = new restaurating();
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(vent, "Terminada la sesión.");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarMouseEntered
        btnRetirar.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnRetirarMouseEntered

    private void btnRetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarMouseExited
        btnRetirar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnRetirarMouseExited

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        btnRetirar.setEnabled(false);
        btnRetirar.setVisible(false);
        retire.setText("");
        tarjeta.setText("");
        recoger.setText("RECOJA");
        recibo.setText("EL RECIBO");
        btnRecoger.setVisible(true);
        btnRecoger.setEnabled(true);
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnRecogerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecogerMouseEntered
        btnRecoger.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnRecogerMouseEntered

    private void btnRecogerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecogerMouseExited
        btnRecoger.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnRecogerMouseExited

    private void btnRecogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecogerActionPerformed
        btnRecoger.setEnabled(false);
        btnRecoger.setVisible(false);
        recoger.setText("");
        recibo.setText("");
        btnVolver.setEnabled(true);
    }//GEN-LAST:event_btnRecogerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecoger;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel horaRecogida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel numeroCola;
    private javax.swing.JLabel qrIMG;
    private javax.swing.JLabel recibo;
    private javax.swing.JLabel recoger;
    private javax.swing.JLabel retire;
    private javax.swing.JLabel tarjeta;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables

    private void escalarImagenQR() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/codigoqr.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(qrIMG.getWidth(), qrIMG.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        qrIMG.setIcon(icon);
    }

    private void escalarImagenTarjeta() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/tarjeta.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnRetirar.setIcon(icon);
    }

    private void escalarImagenTicket() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/ticket.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnRecoger.setIcon(icon);
    }

    private void cambiarHoraRecogida() {
        horaRecogida.setText("");
    }

    private void cambiarNumeroCola() {
        Random r = new Random();
        numeroCola.setText(String.valueOf((int) (Math.random() * 100)) + String.valueOf((char) (r.nextInt(26) + 'A')));
    }
}
