/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.ProductoCarta;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pabli
 */
public class principal extends javax.swing.JFrame {

    private final restaurating sesion;

    /**
     * Creates new form principal
     *
     * @param sesion
     */
    public principal(restaurating sesion) {
        initComponents();
        escalarImagenMenu();
        escalarImagenConfigurar();
        escalarImagenSalir();
        escalarImagenPago();
        escalarImagenCarrito();

        this.sesion = sesion;

        if (!btnCaja.isEnabled()) {
            avisoPago.setText("*Debe añadir algún producto al carrito para poder realizar el pago.");
        } else {
            avisoPago.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPagina = new javax.swing.JLabel();
        registradoraIMG = new javax.swing.JLabel();
        menuDiaIMG = new javax.swing.JLabel();
        btnConfigurar = new javax.swing.JButton();
        btnCaja = new javax.swing.JButton();
        btnPersonalizarMenu = new javax.swing.JButton();
        configuracionIMG = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        avisoPago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Principal");

        tituloPagina.setBackground(new java.awt.Color(255, 102, 102));
        tituloPagina.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tituloPagina.setForeground(new java.awt.Color(255, 102, 102));
        tituloPagina.setText("Página Principal");

        registradoraIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/cajaregistradora.png"))); // NOI18N

        menuDiaIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/menu.jpg"))); // NOI18N
        menuDiaIMG.setPreferredSize(new java.awt.Dimension(400, 400));

        btnConfigurar.setBackground(new java.awt.Color(255, 102, 102));
        btnConfigurar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConfigurar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfigurar.setText("Pedir a la Carta");
        btnConfigurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigurarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigurarMouseExited(evt);
            }
        });
        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });

        btnCaja.setBackground(new java.awt.Color(255, 102, 102));
        btnCaja.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCaja.setText("Pasar a Caja");
        btnCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCaja.setEnabled(false);
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCajaMouseExited(evt);
            }
        });
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });

        btnPersonalizarMenu.setBackground(new java.awt.Color(255, 102, 102));
        btnPersonalizarMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPersonalizarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalizarMenu.setText("Añadir Menú del Día");
        btnPersonalizarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonalizarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalizarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalizarMenuMouseExited(evt);
            }
        });
        btnPersonalizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalizarMenuActionPerformed(evt);
            }
        });

        configuracionIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/anadir.png"))); // NOI18N

        btnCarrito.setBackground(new java.awt.Color(255, 102, 102));
        btnCarrito.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCarrito.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/carrito.png"))); // NOI18N
        btnCarrito.setText("Ver pedido actual");
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCarritoMouseExited(evt);
            }
        });
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Salir");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        avisoPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        avisoPago.setForeground(new java.awt.Color(255, 0, 0));
        avisoPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloPagina)
                        .addGap(366, 366, 366)
                        .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menuDiaIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(configuracionIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(registradoraIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPersonalizarMenu)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(326, 326, 326)
                                        .addComponent(avisoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(btnConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)))))))
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloPagina))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configuracionIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuDiaIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registradoraIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonalizarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(avisoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        configuracion vent = new configuracion(sesion, "principal", "");
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfigurarActionPerformed

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        pago vent = new pago("principal", "", sesion);
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnPersonalizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalizarMenuActionPerformed
        menu vent = new menu(sesion, "principal", "");
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPersonalizarMenuActionPerformed

    private void btnCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseEntered
        if (btnCaja.isEnabled()) {
            btnCaja.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            btnCaja.setBackground(new Color(255, 51, 51));
        }
    }//GEN-LAST:event_btnCajaMouseEntered

    private void btnCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseExited
        btnCaja.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnCajaMouseExited

    private void btnConfigurarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigurarMouseEntered
        btnConfigurar.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnConfigurarMouseEntered

    private void btnConfigurarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigurarMouseExited
        btnConfigurar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnConfigurarMouseExited

    private void btnPersonalizarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalizarMenuMouseEntered
        btnPersonalizarMenu.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnPersonalizarMenuMouseEntered

    private void btnPersonalizarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalizarMenuMouseExited
        btnPersonalizarMenu.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnPersonalizarMenuMouseExited

    private void btnCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseEntered
        btnCarrito.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnCarritoMouseEntered

    private void btnCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseExited
        btnCarrito.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnCarritoMouseExited

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        carrito vent = new carrito("principal", sesion);
        vent.comprobarProductos();
        vent.setLocationRelativeTo(null);
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Perderá todo su progreso. ¿Desea continuar?", "¡Aviso!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if (resp == 0) {
            restaurating vent = new restaurating();
            vent.setLocationRelativeTo(null);
            vent.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoPago;
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnConfigurar;
    private javax.swing.JButton btnPersonalizarMenu;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel configuracionIMG;
    private javax.swing.JLabel menuDiaIMG;
    private javax.swing.JLabel registradoraIMG;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables

    private void escalarImagenMenu() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/menu.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(menuDiaIMG.getWidth(), menuDiaIMG.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        menuDiaIMG.setIcon(icon);
    }

    private void escalarImagenConfigurar() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/anadir.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(configuracionIMG.getWidth(), configuracionIMG.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        configuracionIMG.setIcon(icon);
    }

    private void escalarImagenPago() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/caja.jpg"));
        Image img = icon.getImage();
        img = img.getScaledInstance(registradoraIMG.getWidth(), registradoraIMG.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        registradoraIMG.setIcon(icon);
    }

    private void escalarImagenCarrito() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/carrito.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnCarrito.setIcon(icon);
    }

    private void escalarImagenSalir() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/práctica/pkg4/imagenes/salir.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btnVolver.setIcon(icon);
    }

    public void comprobarProductos() {
        boolean carta = false;
        for (ProductoCarta prod : sesion.productosCarta) {
            if (prod.getCantidad() > 0) {
                carta = true;
                break;
            }
        }

        if (carta || sesion.menu.size() > 0) {
            btnCaja.setEnabled(true);
        } else {
            btnCaja.setEnabled(false);
        }

        if (!btnCaja.isEnabled()) {
            avisoPago.setText("*Debe añadir algún producto al carrito para poder realizar el pago.");
        } else {
            avisoPago.setText("");
        }
    }
}
